import type { OnlineRecipe } from "./recipeSearch";

// A curated, offline set of Indian home recipes — weighted toward Maharashtrian
// / Pune cooking plus pan-Indian staples — because the free online databases
// barely cover regional dishes (Pohe, Upma, Idli…). Quantities are typical
// home portions (~3-4 servings) and methods are concise starting points; the
// importer opens the editor so everything can be tweaked before saving.
//
// `aliases` capture common spellings so a search for "pohe" finds "Kanda Poha".
export interface LocalRecipe extends OnlineRecipe {
  aliases?: string[];
}

function norm(s: string) {
  return s.trim().toLowerCase();
}

export const INDIAN_RECIPES: LocalRecipe[] = [
  {
    id: "in-kanda-poha",
    name: "Kanda Poha",
    area: "Maharashtrian",
    category: "Breakfast",
    thumb: null,
    aliases: ["pohe", "poha", "kanda pohe", "flattened rice"],
    instructions:
      "Rinse the poha in a colander until soft, then drain and let it sit. Heat oil, splutter mustard seeds, add peanuts, curry leaves, green chilli and onion; sauté till soft. Stir in turmeric, salt and sugar, then fold in the poha gently. Cover for 2-3 minutes, finish with lemon juice and coriander.",
    ingredients: [
      { name: "Thick poha", quantity: 2, unit: "cup" },
      { name: "Onion", quantity: 1, unit: "pcs" },
      { name: "Peanuts", quantity: 3, unit: "tbsp" },
      { name: "Green chilli", quantity: 2, unit: "pcs" },
      { name: "Mustard seeds", quantity: 1, unit: "tsp" },
      { name: "Curry leaves", quantity: 8, unit: "pcs" },
      { name: "Turmeric", quantity: 0.25, unit: "tsp" },
      { name: "Sugar", quantity: 1, unit: "tsp" },
      { name: "Lemon", quantity: 0.5, unit: "pcs" },
      { name: "Oil", quantity: 2, unit: "tbsp" },
      { name: "Coriander", quantity: null, unit: null },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-upma",
    name: "Upma",
    area: "South Indian",
    category: "Breakfast",
    thumb: null,
    aliases: ["uppma", "sajjige", "rava upma"],
    instructions:
      "Dry-roast the rava until fragrant and set aside. Heat oil/ghee, splutter mustard seeds, urad dal and curry leaves, then add green chilli, ginger and onion; sauté. Add water and salt, bring to a boil, then rain in the rava while stirring to avoid lumps. Cover and cook 3-4 minutes; finish with lemon and coriander.",
    ingredients: [
      { name: "Rava (semolina)", quantity: 1, unit: "cup" },
      { name: "Onion", quantity: 1, unit: "pcs" },
      { name: "Green chilli", quantity: 2, unit: "pcs" },
      { name: "Ginger", quantity: 1, unit: "tsp" },
      { name: "Mustard seeds", quantity: 1, unit: "tsp" },
      { name: "Urad dal", quantity: 1, unit: "tsp" },
      { name: "Curry leaves", quantity: 8, unit: "pcs" },
      { name: "Water", quantity: 2.5, unit: "cup" },
      { name: "Ghee", quantity: 2, unit: "tbsp" },
      { name: "Lemon", quantity: 0.5, unit: "pcs" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-sabudana-khichdi",
    name: "Sabudana Khichdi",
    area: "Maharashtrian",
    category: "Breakfast",
    thumb: null,
    aliases: ["sabudana", "sago khichdi", "sabudana khichadi"],
    instructions:
      "Soak sabudana overnight with just enough water so pearls are separate and soft. Mix in crushed roasted peanuts, salt and sugar. Heat ghee, fry cumin, green chilli and boiled cubed potato, then add the sabudana. Toss on low heat till translucent; finish with lemon and coriander.",
    ingredients: [
      { name: "Sabudana", quantity: 1, unit: "cup" },
      { name: "Potato", quantity: 1, unit: "pcs" },
      { name: "Peanuts", quantity: 0.5, unit: "cup" },
      { name: "Cumin seeds", quantity: 1, unit: "tsp" },
      { name: "Green chilli", quantity: 2, unit: "pcs" },
      { name: "Sugar", quantity: 1, unit: "tsp" },
      { name: "Ghee", quantity: 2, unit: "tbsp" },
      { name: "Lemon", quantity: 0.5, unit: "pcs" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-thalipeeth",
    name: "Thalipeeth",
    area: "Maharashtrian",
    category: "Breakfast",
    thumb: null,
    aliases: ["thalpeeth", "bhajani thalipeeth"],
    instructions:
      "Mix the flours with chopped onion, coriander, green chilli, turmeric, red chilli powder and salt; add water to a soft dough. Pat a portion directly on an oiled pan or banana leaf into a round and make a hole in the centre. Drizzle oil and cook covered on both sides till crisp. Serve with curd or butter.",
    ingredients: [
      { name: "Bhajani / multigrain flour", quantity: 2, unit: "cup" },
      { name: "Onion", quantity: 1, unit: "pcs" },
      { name: "Coriander", quantity: 0.25, unit: "cup" },
      { name: "Green chilli", quantity: 2, unit: "pcs" },
      { name: "Turmeric", quantity: 0.25, unit: "tsp" },
      { name: "Red chilli powder", quantity: 1, unit: "tsp" },
      { name: "Oil", quantity: 3, unit: "tbsp" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-pithla",
    name: "Pithla",
    area: "Maharashtrian",
    category: "Main",
    thumb: null,
    aliases: ["pithle", "besan pithla", "zunka"],
    instructions:
      "Whisk besan into water to a lump-free slurry. Heat oil, splutter mustard and cumin, add garlic, green chilli, curry leaves and onion; sauté. Pour in the slurry with turmeric and salt, stirring constantly until it thickens. Cook a few minutes more and finish with coriander. Serve with bhakri or rice.",
    ingredients: [
      { name: "Besan (gram flour)", quantity: 1, unit: "cup" },
      { name: "Water", quantity: 2.5, unit: "cup" },
      { name: "Onion", quantity: 1, unit: "pcs" },
      { name: "Garlic", quantity: 4, unit: "pcs" },
      { name: "Green chilli", quantity: 2, unit: "pcs" },
      { name: "Mustard seeds", quantity: 1, unit: "tsp" },
      { name: "Cumin seeds", quantity: 1, unit: "tsp" },
      { name: "Turmeric", quantity: 0.5, unit: "tsp" },
      { name: "Oil", quantity: 2, unit: "tbsp" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-misal",
    name: "Misal Pav",
    area: "Maharashtrian",
    category: "Snack",
    thumb: null,
    aliases: ["misal", "missal", "usal misal"],
    instructions:
      "Cook sprouted moth/matki with turmeric and salt till soft. Make a spicy kat by sautéing onion, garlic, ginger, coconut and goda/misal masala, then blend and simmer with water. Combine the usal with the kat. Top with farsan, chopped onion, coriander and lemon; serve with pav.",
    ingredients: [
      { name: "Matki (moth bean) sprouts", quantity: 2, unit: "cup" },
      { name: "Onion", quantity: 2, unit: "pcs" },
      { name: "Garlic", quantity: 6, unit: "pcs" },
      { name: "Ginger", quantity: 1, unit: "tbsp" },
      { name: "Grated coconut", quantity: 0.25, unit: "cup" },
      { name: "Misal / goda masala", quantity: 2, unit: "tbsp" },
      { name: "Farsan", quantity: 1, unit: "cup" },
      { name: "Pav", quantity: 8, unit: "pcs" },
      { name: "Oil", quantity: 3, unit: "tbsp" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-masale-bhaat",
    name: "Masale Bhaat",
    area: "Maharashtrian",
    category: "Main",
    thumb: null,
    aliases: ["masala bhaat", "masale bhat"],
    instructions:
      "Heat ghee, splutter mustard, cumin, cloves and cinnamon, add curry leaves and chopped vegetables. Stir in goda masala, turmeric and salt, then the soaked rice. Add hot water (about double), bring to a boil and cook covered till done. Rest, fluff, and top with grated coconut and coriander.",
    ingredients: [
      { name: "Rice", quantity: 1.5, unit: "cup" },
      { name: "Mixed vegetables (tendli/brinjal)", quantity: 1.5, unit: "cup" },
      { name: "Goda masala", quantity: 2, unit: "tbsp" },
      { name: "Cumin seeds", quantity: 1, unit: "tsp" },
      { name: "Cloves", quantity: 4, unit: "pcs" },
      { name: "Cinnamon", quantity: 1, unit: "pcs" },
      { name: "Turmeric", quantity: 0.5, unit: "tsp" },
      { name: "Grated coconut", quantity: 0.25, unit: "cup" },
      { name: "Ghee", quantity: 3, unit: "tbsp" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-sheera",
    name: "Sheera (Sooji Halwa)",
    area: "Maharashtrian",
    category: "Dessert",
    thumb: null,
    aliases: ["sheera", "rava sheera", "sooji halwa", "suji halwa"],
    instructions:
      "Roast the rava in ghee on low heat until golden and aromatic. Separately warm water and milk with sugar. Carefully pour the hot liquid into the rava, stirring to avoid lumps. Cook covered till it thickens and leaves the pan; add cardamom and roasted nuts.",
    ingredients: [
      { name: "Rava (semolina)", quantity: 1, unit: "cup" },
      { name: "Sugar", quantity: 0.75, unit: "cup" },
      { name: "Ghee", quantity: 0.5, unit: "cup" },
      { name: "Water", quantity: 1.5, unit: "cup" },
      { name: "Milk", quantity: 0.5, unit: "cup" },
      { name: "Cardamom", quantity: 0.5, unit: "tsp" },
      { name: "Cashew & raisins", quantity: 3, unit: "tbsp" },
    ],
  },
  {
    id: "in-varan-bhaat",
    name: "Varan Bhaat",
    area: "Maharashtrian",
    category: "Main",
    thumb: null,
    aliases: ["varan", "toor dal", "dal rice"],
    instructions:
      "Pressure-cook toor dal with turmeric till soft and mash smooth. Add water to the consistency you like, with salt, a pinch of jaggery and a squeeze of lemon, and simmer. Temper ghee with cumin, mustard, hing and curry leaves and pour over. Serve over hot rice with a spoon of ghee.",
    ingredients: [
      { name: "Toor dal", quantity: 1, unit: "cup" },
      { name: "Rice", quantity: 1, unit: "cup" },
      { name: "Turmeric", quantity: 0.5, unit: "tsp" },
      { name: "Jaggery", quantity: 1, unit: "tsp" },
      { name: "Cumin seeds", quantity: 1, unit: "tsp" },
      { name: "Hing (asafoetida)", quantity: 1, unit: "pcs" },
      { name: "Ghee", quantity: 2, unit: "tbsp" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-idli",
    name: "Idli",
    area: "South Indian",
    category: "Breakfast",
    thumb: null,
    aliases: ["idly", "idlis", "steamed rice cake"],
    instructions:
      "Soak idli rice and urad dal (with fenugreek) separately for 5-6 hours, then grind to a smooth batter and mix with salt. Ferment overnight until risen and airy. Grease idli moulds, pour the batter and steam 10-12 minutes until a tester comes out clean. Serve with sambar and chutney.",
    ingredients: [
      { name: "Idli rice", quantity: 2, unit: "cup" },
      { name: "Urad dal", quantity: 0.5, unit: "cup" },
      { name: "Fenugreek seeds", quantity: 0.5, unit: "tsp" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-dosa",
    name: "Plain Dosa",
    area: "South Indian",
    category: "Breakfast",
    thumb: null,
    aliases: ["dosai", "sada dosa"],
    instructions:
      "Soak rice and urad dal separately for 5-6 hours, grind to a smooth batter, mix with salt and ferment overnight. Thin slightly with water to a pourable consistency. Pour a ladle on a hot greased tawa and spread thin in a spiral; drizzle oil and cook till crisp and golden. Fold and serve with chutney and sambar.",
    ingredients: [
      { name: "Dosa rice", quantity: 2, unit: "cup" },
      { name: "Urad dal", quantity: 0.5, unit: "cup" },
      { name: "Fenugreek seeds", quantity: 0.5, unit: "tsp" },
      { name: "Oil", quantity: 3, unit: "tbsp" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-medu-vada",
    name: "Medu Vada",
    area: "South Indian",
    category: "Snack",
    thumb: null,
    aliases: ["medu wada", "urad vada", "garelu"],
    instructions:
      "Soak urad dal 4 hours, then grind to a thick fluffy batter with minimal water. Beat in salt, pepper, green chilli, ginger and curry leaves. Wet your hand, shape rounds with a hole in the centre, and deep-fry on medium heat till golden and crisp. Serve with chutney and sambar.",
    ingredients: [
      { name: "Urad dal", quantity: 1, unit: "cup" },
      { name: "Green chilli", quantity: 2, unit: "pcs" },
      { name: "Ginger", quantity: 1, unit: "tsp" },
      { name: "Black pepper", quantity: 0.5, unit: "tsp" },
      { name: "Curry leaves", quantity: 8, unit: "pcs" },
      { name: "Oil", quantity: 2, unit: "cup" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-sambar",
    name: "Sambar",
    area: "South Indian",
    category: "Side",
    thumb: null,
    aliases: ["sambhar", "saaru"],
    instructions:
      "Cook toor dal with turmeric till soft and mash. Boil vegetables with tamarind pulp, sambar powder and salt till tender, then add the dal and simmer. Temper ghee/oil with mustard, hing, dried chilli and curry leaves and pour over. Finish with coriander.",
    ingredients: [
      { name: "Toor dal", quantity: 0.75, unit: "cup" },
      { name: "Mixed vegetables (drumstick/pumpkin)", quantity: 2, unit: "cup" },
      { name: "Tamarind", quantity: 1, unit: "tbsp" },
      { name: "Sambar powder", quantity: 2, unit: "tbsp" },
      { name: "Mustard seeds", quantity: 1, unit: "tsp" },
      { name: "Hing (asafoetida)", quantity: 1, unit: "pcs" },
      { name: "Curry leaves", quantity: 10, unit: "pcs" },
      { name: "Oil", quantity: 2, unit: "tbsp" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-coconut-chutney",
    name: "Coconut Chutney",
    area: "South Indian",
    category: "Side",
    thumb: null,
    aliases: ["nariyal chutney", "coconut chatni"],
    instructions:
      "Grind grated coconut with roasted gram dal, green chilli, ginger and salt to a smooth paste, adding water as needed. Temper oil with mustard seeds, urad dal, dried red chilli and curry leaves and stir into the chutney.",
    ingredients: [
      { name: "Grated coconut", quantity: 1, unit: "cup" },
      { name: "Roasted gram dal", quantity: 2, unit: "tbsp" },
      { name: "Green chilli", quantity: 2, unit: "pcs" },
      { name: "Ginger", quantity: 1, unit: "tsp" },
      { name: "Mustard seeds", quantity: 0.5, unit: "tsp" },
      { name: "Curry leaves", quantity: 8, unit: "pcs" },
      { name: "Oil", quantity: 1, unit: "tbsp" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-lemon-rice",
    name: "Lemon Rice",
    area: "South Indian",
    category: "Main",
    thumb: null,
    aliases: ["chitranna", "nimmakaya pulihora"],
    instructions:
      "Cool cooked rice so grains stay separate. Heat oil, splutter mustard, urad dal, chana dal, peanuts, dried chilli and curry leaves, then add turmeric and hing. Turn off heat, mix in lemon juice and salt, then fold in the rice gently.",
    ingredients: [
      { name: "Cooked rice", quantity: 3, unit: "cup" },
      { name: "Lemon", quantity: 1, unit: "pcs" },
      { name: "Peanuts", quantity: 3, unit: "tbsp" },
      { name: "Mustard seeds", quantity: 1, unit: "tsp" },
      { name: "Chana dal", quantity: 1, unit: "tbsp" },
      { name: "Dried red chilli", quantity: 2, unit: "pcs" },
      { name: "Turmeric", quantity: 0.5, unit: "tsp" },
      { name: "Curry leaves", quantity: 10, unit: "pcs" },
      { name: "Oil", quantity: 2, unit: "tbsp" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-dal-tadka",
    name: "Dal Tadka",
    area: "North Indian",
    category: "Main",
    thumb: null,
    aliases: ["dal fry", "tadka dal", "yellow dal"],
    instructions:
      "Pressure-cook toor/moong dal with turmeric and salt till soft, then mash lightly. In ghee, fry cumin, garlic, ginger, green chilli and onion, add tomato and spices and cook to a masala. Stir the masala into the dal with water to taste and simmer. Finish with a chilli-ghee tadka and coriander.",
    ingredients: [
      { name: "Toor dal", quantity: 1, unit: "cup" },
      { name: "Onion", quantity: 1, unit: "pcs" },
      { name: "Tomato", quantity: 2, unit: "pcs" },
      { name: "Garlic", quantity: 5, unit: "pcs" },
      { name: "Ginger", quantity: 1, unit: "tbsp" },
      { name: "Cumin seeds", quantity: 1, unit: "tsp" },
      { name: "Turmeric", quantity: 0.5, unit: "tsp" },
      { name: "Red chilli powder", quantity: 1, unit: "tsp" },
      { name: "Ghee", quantity: 2, unit: "tbsp" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-rajma",
    name: "Rajma Masala",
    area: "North Indian",
    category: "Main",
    thumb: null,
    aliases: ["rajma", "kidney bean curry"],
    instructions:
      "Soak rajma overnight and pressure-cook till very soft. Make a masala by sautéing onion, ginger-garlic, tomato and spices in oil till it leaves oil. Add the rajma with its water and simmer 15-20 minutes, mashing a few beans to thicken. Finish with garam masala and coriander.",
    ingredients: [
      { name: "Rajma (kidney beans)", quantity: 1, unit: "cup" },
      { name: "Onion", quantity: 2, unit: "pcs" },
      { name: "Tomato", quantity: 3, unit: "pcs" },
      { name: "Ginger-garlic paste", quantity: 1, unit: "tbsp" },
      { name: "Cumin seeds", quantity: 1, unit: "tsp" },
      { name: "Red chilli powder", quantity: 1, unit: "tsp" },
      { name: "Garam masala", quantity: 1, unit: "tsp" },
      { name: "Oil", quantity: 3, unit: "tbsp" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-chole",
    name: "Chole (Chana Masala)",
    area: "Punjabi",
    category: "Main",
    thumb: null,
    aliases: ["chana masala", "chhole", "chickpea curry"],
    instructions:
      "Soak chickpeas overnight and pressure-cook till soft. Sauté onion, ginger-garlic and tomato with chole masala, cumin, chilli and turmeric to a thick masala. Add the chickpeas with water and simmer till the gravy thickens. Finish with garam masala, a squeeze of lemon and coriander.",
    ingredients: [
      { name: "Chickpeas (kabuli chana)", quantity: 1, unit: "cup" },
      { name: "Onion", quantity: 2, unit: "pcs" },
      { name: "Tomato", quantity: 2, unit: "pcs" },
      { name: "Ginger-garlic paste", quantity: 1, unit: "tbsp" },
      { name: "Chole masala", quantity: 2, unit: "tbsp" },
      { name: "Cumin seeds", quantity: 1, unit: "tsp" },
      { name: "Lemon", quantity: 0.5, unit: "pcs" },
      { name: "Oil", quantity: 3, unit: "tbsp" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-palak-paneer",
    name: "Palak Paneer",
    area: "North Indian",
    category: "Main",
    thumb: null,
    aliases: ["spinach paneer", "saag paneer"],
    instructions:
      "Blanch spinach briefly, then blend to a smooth puree. Sauté cumin, ginger-garlic, green chilli and onion, add tomato and spices and cook down. Stir in the puree with a little water and simmer. Add paneer cubes and a swirl of cream; warm through.",
    ingredients: [
      { name: "Spinach (palak)", quantity: 1, unit: "kg" },
      { name: "Paneer", quantity: 250, unit: "g" },
      { name: "Onion", quantity: 1, unit: "pcs" },
      { name: "Tomato", quantity: 2, unit: "pcs" },
      { name: "Ginger-garlic paste", quantity: 1, unit: "tbsp" },
      { name: "Cumin seeds", quantity: 1, unit: "tsp" },
      { name: "Garam masala", quantity: 1, unit: "tsp" },
      { name: "Cream", quantity: 2, unit: "tbsp" },
      { name: "Oil", quantity: 2, unit: "tbsp" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-paneer-butter-masala",
    name: "Paneer Butter Masala",
    area: "North Indian",
    category: "Main",
    thumb: null,
    aliases: ["paneer makhani", "butter paneer"],
    instructions:
      "Simmer onion, tomato, cashews, ginger and garlic till soft, then blend to a smooth gravy. Cook in butter with chilli powder and a little water, season with salt, sugar and garam masala. Add paneer cubes, kasuri methi and cream; simmer a few minutes.",
    ingredients: [
      { name: "Paneer", quantity: 250, unit: "g" },
      { name: "Tomato", quantity: 4, unit: "pcs" },
      { name: "Onion", quantity: 1, unit: "pcs" },
      { name: "Cashews", quantity: 12, unit: "pcs" },
      { name: "Butter", quantity: 3, unit: "tbsp" },
      { name: "Cream", quantity: 3, unit: "tbsp" },
      { name: "Red chilli powder", quantity: 1, unit: "tsp" },
      { name: "Garam masala", quantity: 1, unit: "tsp" },
      { name: "Kasuri methi", quantity: 1, unit: "tsp" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-aloo-gobi",
    name: "Aloo Gobi",
    area: "North Indian",
    category: "Side",
    thumb: null,
    aliases: ["potato cauliflower", "gobi aloo"],
    instructions:
      "Heat oil, fry cumin, then add potato and cauliflower florets with turmeric, chilli, coriander powder and salt. Toss to coat, cover and cook on low, stirring occasionally, till tender. Uncover to crisp slightly; finish with garam masala and coriander.",
    ingredients: [
      { name: "Potato", quantity: 2, unit: "pcs" },
      { name: "Cauliflower", quantity: 1, unit: "pcs" },
      { name: "Cumin seeds", quantity: 1, unit: "tsp" },
      { name: "Turmeric", quantity: 0.5, unit: "tsp" },
      { name: "Coriander powder", quantity: 1, unit: "tbsp" },
      { name: "Red chilli powder", quantity: 1, unit: "tsp" },
      { name: "Garam masala", quantity: 0.5, unit: "tsp" },
      { name: "Oil", quantity: 3, unit: "tbsp" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-jeera-rice",
    name: "Jeera Rice",
    area: "North Indian",
    category: "Side",
    thumb: null,
    aliases: ["cumin rice", "zeera rice"],
    instructions:
      "Rinse and soak basmati rice 20 minutes. Heat ghee, splutter cumin with a bay leaf and whole spices. Add the drained rice, toss, then add water and salt. Cook covered on low till done, rest, and fluff.",
    ingredients: [
      { name: "Basmati rice", quantity: 1, unit: "cup" },
      { name: "Cumin seeds", quantity: 1.5, unit: "tsp" },
      { name: "Bay leaf", quantity: 1, unit: "pcs" },
      { name: "Water", quantity: 1.75, unit: "cup" },
      { name: "Ghee", quantity: 2, unit: "tbsp" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-aloo-paratha",
    name: "Aloo Paratha",
    area: "Punjabi",
    category: "Breakfast",
    thumb: null,
    aliases: ["alu paratha", "potato paratha"],
    instructions:
      "Knead a soft wheat dough and rest. Mash boiled potato with green chilli, ginger, coriander, chilli powder, amchur and salt. Stuff a portion into a dough ball, seal and roll out gently. Cook on a hot tawa with ghee till golden brown on both sides.",
    ingredients: [
      { name: "Wheat flour", quantity: 2, unit: "cup" },
      { name: "Potato", quantity: 3, unit: "pcs" },
      { name: "Green chilli", quantity: 2, unit: "pcs" },
      { name: "Ginger", quantity: 1, unit: "tsp" },
      { name: "Coriander", quantity: 0.25, unit: "cup" },
      { name: "Amchur (dry mango)", quantity: 1, unit: "tsp" },
      { name: "Red chilli powder", quantity: 1, unit: "tsp" },
      { name: "Ghee", quantity: 3, unit: "tbsp" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
  {
    id: "in-moong-khichdi",
    name: "Moong Dal Khichdi",
    area: "Indian",
    category: "Main",
    thumb: null,
    aliases: ["khichdi", "khichadi", "dal khichdi"],
    instructions:
      "Rinse rice and moong dal together. Heat ghee, fry cumin, hing, ginger and a pinch of turmeric. Add the rice-dal, water and salt and pressure-cook to a soft, porridge-like consistency. Serve hot with a spoon of ghee and papad.",
    ingredients: [
      { name: "Rice", quantity: 0.75, unit: "cup" },
      { name: "Moong dal", quantity: 0.5, unit: "cup" },
      { name: "Cumin seeds", quantity: 1, unit: "tsp" },
      { name: "Hing (asafoetida)", quantity: 1, unit: "pcs" },
      { name: "Ginger", quantity: 1, unit: "tsp" },
      { name: "Turmeric", quantity: 0.5, unit: "tsp" },
      { name: "Water", quantity: 4, unit: "cup" },
      { name: "Ghee", quantity: 2, unit: "tbsp" },
      { name: "Salt", quantity: null, unit: null },
    ],
  },
];

// Search the local set by name, alias, or an ingredient name. Returns plain
// OnlineRecipe objects (aliases stripped) tagged as a local source.
export function searchLocalRecipes(query: string): OnlineRecipe[] {
  const q = norm(query);
  if (q.length < 2) return [];
  return INDIAN_RECIPES.filter((r) => {
    if (norm(r.name).includes(q)) return true;
    if (r.aliases?.some((a) => norm(a).includes(q) || q.includes(norm(a)))) return true;
    return r.ingredients.some((i) => norm(i.name).includes(q));
  }).map(({ aliases: _aliases, ...r }) => ({ ...r, source: "local" as const }));
}
